# Generated by Django 4.2 on 2024-01-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeniedIPAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP-адрес")),
                (
                    "attempted_path",
                    models.CharField(blank=True, max_length=512, verbose_name="Запрошенный путь"),
                ),
                (
                    "attempted_method",
                    models.CharField(blank=True, max_length=12, verbose_name="HTTP метод"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                ("reason", models.CharField(blank=True, max_length=255, verbose_name="Причина")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время")),
            ],
            options={
                "verbose_name": "Заблокированный IP",
                "verbose_name_plural": "Заблокированные IP",
                "indexes": [
                    models.Index(fields=["ip_address"], name="core_denied_ip_idx"),
                    models.Index(fields=["created_at"], name="core_denied_ip_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserIPRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP-адрес")),
                (
                    "first_seen_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Первое посещение"),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(auto_now=True, verbose_name="Последнее посещение"),
                ),
                (
                    "last_path",
                    models.CharField(blank=True, max_length=512, verbose_name="Последний путь"),
                ),
                (
                    "last_method",
                    models.CharField(blank=True, max_length=12, verbose_name="Последний метод"),
                ),
                ("last_user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "last_download_path",
                    models.CharField(blank=True, max_length=512, verbose_name="Последняя загрузка"),
                ),
                (
                    "last_download_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Последняя загрузка (время)"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP пользователя",
                "verbose_name_plural": "IP пользователей",
            },
        ),
        migrations.AddConstraint(
            model_name="useriprecord",
            constraint=models.UniqueConstraint(fields=("user", "ip_address"), name="core_user_ip_unique"),
        ),
        migrations.AddIndex(
            model_name="useriprecord",
            index=models.Index(fields=["user"], name="core_user_ip_user_idx"),
        ),
        migrations.AddIndex(
            model_name="useriprecord",
            index=models.Index(fields=["ip_address"], name="core_user_ip_ip_idx"),
        ),
    ]
