# Generated by Django 6.0.1 on 2026-01-29 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('rca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatroom',
            name='chat_room_direct_key_required',
        ),
        migrations.RemoveConstraint(
            model_name='chatroom',
            name='chat_room_group_name_required',
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direct_key__isnull', False), ('room_type', 'direct')), ('room_type', 'group'), _connector='OR'), name='chat_room_direct_key_required'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name__isnull', False), ('room_type', 'group')), ('room_type', 'direct'), _connector='OR'), name='chat_room_group_name_required'),
        ),
    ]
