# Generated by ChatGPT on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_chatroom_chat_room_direct_key_required_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatmembership",
            index=models.Index(fields=["user", "room"], name="chat_membership_user_room_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "is_deleted", "sent_at"],
                name="chat_msg_room_del_sent_idx",
            ),
        ),
    ]
