# Generated by Django 5.x on 2026-01-30

from django.db import migrations, models
import django.db.models.deletion

from osiris.apps.polls.models import validate_image_file

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workplace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(unique=True, verbose_name="IP-адрес")),
                ("label", models.CharField(blank=True, max_length=255, verbose_name="Метка")),
                ("department", models.CharField(blank=True, max_length=255, verbose_name="Подразделение")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
            ],
            options={
                "verbose_name": "Рабочее место",
                "verbose_name_plural": "Рабочие места",
                "ordering": ["ip_address"],
            },
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("published", "Опубликовано"),
                            ("closed", "Закрыто"),
                            ("archived", "Архив"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True, verbose_name="Начало")),
                ("end_at", models.DateTimeField(blank=True, null=True, verbose_name="Окончание")),
                (
                    "identity_mode",
                    models.CharField(
                        choices=[
                            ("anon_ip", "Анонимно (по IP)"),
                            ("name_required", "С ФИО (обязательно)"),
                        ],
                        default="anon_ip",
                        max_length=30,
                    ),
                ),
                (
                    "vote_policy",
                    models.CharField(
                        choices=[
                            ("single", "Один голос"),
                            ("revote_until_end", "Переголосование до конца"),
                        ],
                        default="single",
                        max_length=30,
                    ),
                ),
                (
                    "show_results_to_users",
                    models.BooleanField(default=False, verbose_name="Показывать результаты"),
                ),
                ("audience_all", models.BooleanField(default=True, verbose_name="Вся аудитория")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Голосование",
                "verbose_name_plural": "Голосования",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=500, verbose_name="Вопрос")),
                ("help_text", models.CharField(blank=True, max_length=500, verbose_name="Подсказка")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("single", "Один вариант"),
                            ("multi", "Несколько вариантов"),
                            ("text", "Текст"),
                            ("select", "Выпадающий список"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=True, verbose_name="Обязательный")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="polls/questions/",
                        validators=[validate_image_file],
                        verbose_name="Изображение",
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="Видео ссылка")),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="polls.poll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=255, verbose_name="Вариант")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="polls.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант",
                "verbose_name_plural": "Варианты",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("voter_ip", models.GenericIPAddressField(verbose_name="IP-адрес")),
                ("full_name", models.CharField(blank=True, max_length=255, verbose_name="ФИО")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.poll",
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="votes",
                        to="polls.workplace",
                    ),
                ),
            ],
            options={"verbose_name": "Голос", "verbose_name_plural": "Голоса"},
        ),
        migrations.CreateModel(
            name="VoteAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answer_text", models.TextField(blank=True)),
                (
                    "choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.choice",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="polls.question",
                    ),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="polls.vote",
                    ),
                ),
            ],
            options={"verbose_name": "Ответ", "verbose_name_plural": "Ответы"},
        ),
        migrations.AddField(
            model_name="poll",
            name="audience_workplaces",
            field=models.ManyToManyField(blank=True, related_name="polls", to="polls.workplace", verbose_name="Аудитория"),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(fields=("poll", "voter_ip"), name="polls_unique_vote"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["poll", "voter_ip"], name="polls_vote_ip_idx"),
        ),
        migrations.AddIndex(
            model_name="voteanswer",
            index=models.Index(fields=["question"], name="polls_answer_question_idx"),
        ),
        migrations.AddIndex(
            model_name="voteanswer",
            index=models.Index(fields=["choice"], name="polls_answer_choice_idx"),
        ),
    ]
