# Generated by ChatGPT on 2025-09-07
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="PanelPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Panel permission",
                "verbose_name_plural": "Panel permissions",
                "permissions": [
                    ("core_security_view", "Can view core security panel"),
                ],
            },
        ),
    ]
