# Generated by ChatGPT

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="panelpermission",
            options={
                "permissions": [
                    ("core_security_view", "Can view core security panel"),
                    ("core_users_manage", "Can manage core users"),
                ],
                "verbose_name": "Panel permission",
                "verbose_name_plural": "Panel permissions",
            },
        ),
    ]
