# Generated by ChatGPT
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "set_date",
                    models.DateField(
                        db_index=True,
                        help_text="Дата, за которую был выполнен импорт данных",
                        unique=True,
                        verbose_name="Дата набора данных",
                    ),
                ),
                (
                    "set_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Контрольная сумма всего набора данных",
                        max_length=64,
                        verbose_name="Хеш набора",
                    ),
                ),
                (
                    "org_hash",
                    models.CharField(
                        blank=True,
                        help_text="Хеш данных по организационным единицам",
                        max_length=64,
                        null=True,
                        verbose_name="Хеш организаций",
                    ),
                ),
                (
                    "post_hash",
                    models.CharField(
                        blank=True,
                        help_text="Хеш данных по должностям",
                        max_length=64,
                        null=True,
                        verbose_name="Хеш должностей",
                    ),
                ),
                (
                    "employee_hash",
                    models.CharField(
                        blank=True,
                        help_text="Хеш данных по сотрудникам",
                        max_length=64,
                        null=True,
                        verbose_name="Хеш сотрудников",
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Дата и время загрузки данных в систему",
                        verbose_name="Время импорта",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="duckdb",
                        help_text="Система-источник данных (duckdb, 1C и т.д.)",
                        max_length=50,
                        verbose_name="Источник данных",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пакет импорта",
                "verbose_name_plural": "Пакеты импорта",
                "ordering": ["-set_date"],
            },
        ),
        migrations.CreateModel(
            name="Org",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        help_text="Уникальный идентификатор организационной единицы",
                        max_length=64,
                        unique=True,
                        verbose_name="Код орг.единицы",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организационная единица",
                "verbose_name_plural": "Организационные единицы",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        help_text="Уникальный идентификатор должности",
                        max_length=32,
                        unique=True,
                        verbose_name="Код должности",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "snils_norm",
                    models.CharField(
                        help_text="СНИЛС в формате 11 цифр без разделителей",
                        max_length=11,
                        unique=True,
                        verbose_name="СНИЛС (нормализованный)",
                    ),
                ),
                (
                    "snils_raw_last",
                    models.CharField(
                        blank=True,
                        help_text="СНИЛС в исходном формате из последней выгрузки",
                        max_length=32,
                        null=True,
                        verbose_name="СНИЛС (последний сырой)",
                    ),
                ),
                (
                    "tab_norm_current",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Нормализованный табельный номер на текущий момент",
                        max_length=32,
                        null=True,
                        verbose_name="Табельный номер (текущий)",
                    ),
                ),
                (
                    "tab_raw_last",
                    models.CharField(
                        blank=True,
                        help_text="Табельный номер в исходном формате из последней выгрузки",
                        max_length=32,
                        null=True,
                        verbose_name="Табельный номер (последний сырой)",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Фамилия сотрудника",
                        max_length=128,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Имя сотрудника",
                        max_length=128,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Отчество сотрудника",
                        max_length=128,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(help_text="Дата рождения сотрудника", verbose_name="Дата рождения"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        help_text="Пол сотрудника",
                        max_length=32,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "is_fired_current",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Текущий статус увольнения сотрудника",
                        verbose_name="Уволен",
                    ),
                ),
                (
                    "fired_date_current",
                    models.DateField(
                        blank=True,
                        help_text="Дата увольнения на текущий момент",
                        null=True,
                        verbose_name="Дата увольнения (текущая)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления записи",
                        verbose_name="Дата обновления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["snils_norm"],
            },
        ),
        migrations.CreateModel(
            name="OrgVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Краткое наименование организационной единицы",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Полное официальное наименование",
                        max_length=512,
                        verbose_name="Полное наименование",
                    ),
                ),
                (
                    "parent_code",
                    models.CharField(
                        blank=True,
                        help_text="Код орг.единицы, в которую входит данная",
                        max_length=64,
                        null=True,
                        verbose_name="Код родительской орг.единицы",
                    ),
                ),
                (
                    "is_top",
                    models.BooleanField(
                        default=False,
                        help_text="Флаг, указывающий что это верхнеуровневая орг.единица",
                        verbose_name="Является вершиной",
                    ),
                ),
                (
                    "row_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Контрольная сумма данных версии",
                        max_length=64,
                        verbose_name="Хеш строки данных",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        db_index=True,
                        help_text="Дата начала действия данной версии",
                        verbose_name="Действует с",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Дата окончания действия данной версии",
                        null=True,
                        verbose_name="Действует до",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Флаг актуальной (последней) версии",
                        verbose_name="Текущая версия",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Ссылка на базовую орг.единицу",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="rca.org",
                        verbose_name="Организационная единица",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия орг.единицы",
                "verbose_name_plural": "Версии орг.единиц",
                "ordering": ["org", "-valid_from"],
                "indexes": [
                    models.Index(fields=["org", "is_current"], name="rca_orgversio_org_is_current_idx"),
                    models.Index(fields=["org", "valid_from"], name="rca_orgversio_org_valid_from_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PostVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Полное наименование должности",
                        max_length=512,
                        verbose_name="Наименование должности",
                    ),
                ),
                (
                    "row_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Контрольная сумма данных версии",
                        max_length=64,
                        verbose_name="Хеш строки данных",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        db_index=True,
                        help_text="Дата начала действия данной версии",
                        verbose_name="Действует с",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Дата окончания действия данной версии",
                        null=True,
                        verbose_name="Действует до",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Флаг актуальной (последней) версии",
                        verbose_name="Текущая версия",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Ссылка на базовую должность",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="rca.post",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия должности",
                "verbose_name_plural": "Версии должностей",
                "ordering": ["post", "-valid_from"],
                "indexes": [
                    models.Index(fields=["post", "is_current"], name="rca_postvers_post_is_current_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "snils_raw",
                    models.CharField(
                        blank=True,
                        help_text="СНИЛС в исходном формате из выгрузки",
                        max_length=32,
                        null=True,
                        verbose_name="СНИЛС (сырой)",
                    ),
                ),
                (
                    "tab_raw",
                    models.CharField(
                        blank=True,
                        help_text="Табельный номер в исходном формате из выгрузки",
                        max_length=32,
                        null=True,
                        verbose_name="Табельный номер (сырой)",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="Рабочее состояние (активен, в отпуске и т.д.)",
                        max_length=64,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        help_text="Особые условия или характеристики",
                        max_length=128,
                        verbose_name="Особенность",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Дата приёма на работу", verbose_name="Дата приёма"),
                ),
                (
                    "fire_date",
                    models.DateField(help_text="Дата увольнения или планируемого увольнения", verbose_name="Дата увольнения"),
                ),
                (
                    "vacation_start",
                    models.DateField(
                        blank=True,
                        help_text="Дата начала отпуска",
                        null=True,
                        verbose_name="Начало отпуска",
                    ),
                ),
                (
                    "vacation_end",
                    models.DateField(
                        blank=True,
                        help_text="Дата окончания отпуска",
                        null=True,
                        verbose_name="Окончание отпуска",
                    ),
                ),
                (
                    "office_location",
                    models.CharField(
                        blank=True,
                        help_text="Физическое расположение рабочего места",
                        max_length=512,
                        null=True,
                        verbose_name="Место работы",
                    ),
                ),
                (
                    "row_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Контрольная сумма данных снапшота",
                        max_length=64,
                        verbose_name="Хеш строки данных",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        db_index=True,
                        help_text="Дата начала действия данного снапшота",
                        verbose_name="Действует с",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Дата окончания действия данного снапшота",
                        null=True,
                        verbose_name="Действует до",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Флаг актуального (последнего) снапшота",
                        verbose_name="Текущий снапшот",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Пакет данных, из которого создан снапшот",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_snapshots",
                        to="rca.importbatch",
                        verbose_name="Пакет импорта",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Ссылка на сотрудника",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="rca.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Орг.единица, в которой работает сотрудник",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_snapshots",
                        to="rca.org",
                        verbose_name="Организационная единица",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Должность сотрудника",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_snapshots",
                        to="rca.post",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Снимок состояния сотрудника",
                "verbose_name_plural": "Снимки состояний сотрудников",
                "ordering": ["employee", "-valid_from"],
                "indexes": [
                    models.Index(fields=["employee", "is_current"], name="rca_empsnap_employee_is_current_idx"),
                    models.Index(fields=["org", "is_current"], name="rca_empsnap_org_is_current_idx"),
                    models.Index(fields=["post", "is_current"], name="rca_empsnap_post_is_current_idx"),
                    models.Index(fields=["valid_from"], name="rca_empsnap_valid_from_idx"),
                    models.Index(fields=["valid_to"], name="rca_empsnap_valid_to_idx"),
                    models.Index(fields=["is_current"], name="rca_empsnap_is_current_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VacationPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start",
                    models.DateField(help_text="Дата начала периода отпуска", verbose_name="Начало отпуска"),
                ),
                (
                    "end",
                    models.DateField(help_text="Дата окончания периода отпуска", verbose_name="Окончание отпуска"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Пакет данных, из которого создана запись",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacation_periods",
                        to="rca.importbatch",
                        verbose_name="Пакет импорта",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Сотрудник, которому принадлежит отпуск",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacations",
                        to="rca.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "source_snapshot",
                    models.ForeignKey(
                        help_text="Снапшот сотрудника, содержащий информацию об отпуске",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacation_periods",
                        to="rca.employeesnapshot",
                        verbose_name="Исходный снапшот",
                    ),
                ),
            ],
            options={
                "verbose_name": "Период отпуска",
                "verbose_name_plural": "Периоды отпусков",
                "ordering": ["employee", "-start"],
                "indexes": [
                    models.Index(fields=["employee", "start"], name="rca_vacation_employee_start_idx"),
                    models.Index(fields=["employee", "end"], name="rca_vacation_employee_end_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["tab_norm_current"], name="rca_employee_tab_norm_current_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["is_fired_current"], name="rca_employee_is_fired_current_idx"),
        ),
    ]
